import Head from "next/head";
import Image from "next/image";

import Banner from "../components/banner";
import styles from "../styles/Home.module.css";

// it's the default route bc the file is called index
export default function Home() {
  // console.log("styles for Home", styles);

  const handleOnBannerBtnClick = () => {
    console.log("click");
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Coffee Connoisseur</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <Banner
          buttonText="View stores nearby"
          handleOnClick={handleOnBannerBtnClick}
        />
      </main>
    </div>
  );
}
