import Head from "next/head";
import Banner from "../components/banner/banner";
import Navbar from "../components/nav/navbar";
import styles from "../styles/Home.module.css";
import SectionCards from "../components/card/section-cards";
import {
  getPopularVideos,
  getVideos,
  getWatchItAgainVideos,
} from "../lib/video";
// import { verifyToken } from "../lib/utils";
import { redirectUser } from "../utils/redirectUser";

// import { startFetchMyQuery } from "../lib/db/hasura";

// import { magic } from "../lib/magic-client";

// SERVER SIDE RENDERING (SSR)
// - can only be exported from a page file
// - meant for all routes

// getServersideProps:
// - only runs on server side
// - won't be included in client bundle (bc it's oversight code, it's only going to run on the server)
// - on dev, runs on client and server side

// Page is generated on each request
export async function getServerSideProps(context) {
  // const token = context.req ? context.req?.cookies.token : null;
  // const userId = verifyToken(token);
  const { userId, token } = redirectUser(context);

  if (!userId) {
    return {
      props: {},
      redirect: {
        destination: "/login",
        permanent: false,
      },
    };
  }

  // Fetch data from external API
  const disneyVideos = await getVideos("disney trailer");
  const productivityVideos = await getVideos("productivity");
  const travelVideos = await getVideos("travel");
  const popularVideos = await getPopularVideos();

  // const userId = "did:ethr:0x277EEb9780012626245BBc7E3d625067397C8CF5";
  // const token =
  //   "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3N1ZXIiOiJkaWQ6ZXRocjoweDI3N0VFYjk3ODAwMTI2MjYyNDVCQmM3RTNkNjI1MDY3Mzk3QzhDRjUiLCJwdWJsaWNBZGRyZXNzIjoiMHgyNzdFRWI5NzgwMDEyNjI2MjQ1QkJjN0UzZDYyNTA2NzM5N0M4Q0Y1IiwiZW1haWwiOiJraWxnZW1AbGl2ZS5mciIsIm9hdXRoUHJvdmlkZXIiOm51bGwsInBob25lTnVtYmVyIjpudWxsLCJpYXQiOjE2NjMwODEwNDYsImV4cCI6MTY2MzY4NTg0NiwiaHR0cHM6Ly9oYXN1cmEuaW8vand0L2NsYWltcyI6eyJ4LWhhc3VyYS1hbGxvd2VkLXJvbGVzIjpbInVzZXIiLCJhZG1pbiJdLCJ4LWhhc3VyYS1kZWZhdWx0LXJvbGUiOiJ1c2VyIiwieC1oYXN1cmEtdXNlci1pZCI6ImRpZDpldGhyOjB4Mjc3RUViOTc4MDAxMjYyNjI0NUJCYzdFM2Q2MjUwNjczOTdDOENGNSJ9fQ.gmjkBawwFBFwxKBQYYC3fUetIQbaABgu71ekHb8RQeA";

  const watchItAgainVideos = await getWatchItAgainVideos(userId, token);

  console.log({ watchItAgainVideos });

  // Pass data to the page via props
  return {
    props: {
      disneyVideos,
      productivityVideos,
      travelVideos,
      popularVideos,
      watchItAgainVideos,
    },
  };
}

export default function Home(props) {
  // const disneyVideos = getVideos();
  const {
    disneyVideos,
    productivityVideos,
    travelVideos,
    popularVideos,
    watchItAgainVideos = [],
  } = props;

  // startFetchMyQuery();

  return (
    <div className={styles.container}>
      <Head>
        <title>Netflix</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.main}>
        <Navbar />
        <Banner
          videoId="4zH5iYM4wJo"
          title="Clifford the red dog"
          subTitle="a very cute dog"
          imgUrl="/static/clifford.jpg"
        />
        <div className={styles.sectionWrapper}>
          <SectionCards title="Disney" videos={disneyVideos} size="large" />
          <SectionCards
            title="Watch it again"
            videos={watchItAgainVideos}
            size="small"
          />
          <SectionCards title="Travel" videos={travelVideos} size="small" />
          <SectionCards
            title="Productivity"
            videos={productivityVideos}
            size="medium"
          />
          <SectionCards title="Popular" videos={popularVideos} size="small" />
        </div>
      </div>
    </div>
  );
}
